[package]
name = "cjvm"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = { version = "1.1.9", features = ["serde"] }
clap = { version = "4.5.37", features = ["derive"] }
rc-zip-sync = "4.3.0"
